# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PDMVVMExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  platform :ios, '9.0'
  use_frameworks!
  inhibit_all_warnings!
  
  pod 'ReactiveCocoa', '~> 8.0'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  # Pods for PDMVVMExample

end
